name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      # Install dependencies and build the project
      - run: |
          cd Raider.Gaming
          npm install
          npm run build

      # Setup GitHub Pages
      - uses: actions/configure-pages@v3

      # Upload the build artifacts
      - uses: actions/upload-pages-artifact@v1
        with:
          # Upload the dist directory from Raider.Gaming
          path: Raider.Gaming/dist

      # Deploy to GitHub Pages
      - id: deployment
        uses: actions/deploy-pages@v1
